language: node_js
nodejs: 8.15.0
cache: yarn


install:
  - yarn install

script:
  - yarn test
  - yarn run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: gh-pages

    
notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify

# before_install:
# install:
# before_script:
# script:
# after_success:
# after_failure:
# after_script:
# before_deploy:
# deploy:
# after_deploy: